# Generated by Django 3.1.4 on 2021-01-05 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210105_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='fs_user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
