# Generated by Django 3.1.4 on 2021-01-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fs_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fs_user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='fs_user',
            name='uuid',
        ),
    ]
